version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - misspell
    - gocyclo
  disable:
    - revive
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: var-naming
        disabled: false
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - revive
    - path: e2e/
      linters:
        - gosec
        - errcheck
        - revive
    - path: tests/
      linters:
        - gosec
        - errcheck
        - revive
    - linters:
        - revive
      text: "package-comments"
    - linters:
        - revive
      text: "unused-parameter"
    - linters:
        - revive
      text: "var-naming"
    - linters:
        - gosec
      text: "G304"
    - linters:
        - gosec
      text: "G306"

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
